<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Helthcheck</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.4" />
    <ProjectReference Include="..\..\src\Helthcheck.EntityFrameworkCore\Helthcheck.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\Helthcheck.Application.Tests\Helthcheck.Application.Tests.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="8.3.3" />

  </ItemGroup>

</Project>
